### ISSUE TITLE
Note which python this targets

### ISSUE THREAD

**Issue by mafrosis** [justengel/dataclass_property#1]
Should note in the README which Python this library targets

```
/usr/local/lib/python3.7/site-packages/dataclass_property/__init__.py:6: in <module>
    from .internals import dataclass, field_property
E     File "/usr/local/lib/python3.7/site-packages/dataclass_property/internals.py", line 59
E       def dataclass(cls=None, /, *, init=True, repr=True, eq=True, order=False,
E                               ^
E   SyntaxError: invalid syntax
```

I'm running Python 3.7.9.

**Comment by justengel** [comment]
I did not intend to make this for for Python 3.8+. Thank you for pointing this out. Version 1.1.1 has the forward slash removed.

**Comment by mafrosis** [comment]
Great library by the way! I had just concluded I needed to write something like this myself.. And you have already done it 😅

**Comment by justengel** [comment]
Thanks! I tried getting what I wanted to work with Pydantic, but had some trouble. I made this library as a result, but still wasn't all that happy. In the end I made the 'serial_json' library to do what I wanted. You may want to check out that library.

**Comment by mafrosis** [comment]
Interesting. I'm looking to support properties on dataclasses in my jira CLI project:
https://github.com/mafrosis/jira-offline/blob/master/jira_offline/models.py#L219

That project also includes a [lightweight dataclass<->JSON serializer based on types](https://github.com/mafrosis/jira-offline/blob/master/jira_offline/utils/serializer.py) - which I wrote to solve my problem before I knew Pydantic was a thing..
