### ISSUE TITLE
Suggestion: Factor out the weekdays and datetime utils submodules 

### ISSUE THREAD

**Issue by jmetz** [justengel/dataclass_property#2]
I just came across this useful extension to dataclasses, but was a bit thrown back back by the fact that half of this code seems to deal with something entirely different to the problem seemingly  being addressed. 

Perhaps the `datetime_utils` and `weekdays_lists` submodules should be split off into their own module? I see no direct cross-over from these into the `internals` submodule, which actually handles the crux of what this module seems to be about. 

Would recommend a dependent project, `dataclass_dateproperty` which lists this module as it's core dependency. 

Helps keep this module clean and simpler for those who don't need date-specific properties.

**Comment by justengel** [comment]
I moved the datetime_utils and weekdays_lists into a new package dataclass-dateproperty. This was done in dataclass-property 1.2.0
